apiVersion: v1
kind: Service
metadata:
  name: carts-db
  namespace: sock-shop
  labels:
    app: carts-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: carts-db

--- 

apiVersion: v1
kind: Service
metadata:
  name: carts
  namespace: sock-shop
  labels:
    app: carts 
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: carts

--- 

apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  namespace: sock-shop
  labels:
    app: catalogue-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: catalogue-db

---

apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: sock-shop
  labels:
    app: catalogue
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: catalogue

---

apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: sock-shop
  labels:
    app: front-end
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30080
  selector:
    app: front-end

--- 

apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: sock-shop
  labels:
    app: orders-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: orders-db

---

apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: sock-shop
  labels:
    app: orders
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: orders

---

apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: sock-shop
  labels:
    app: payment 
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: payment

---

apiVersion: v1
kind: Service
metadata:
  name: queue-master
  annotations:
    prometheus.io/path: "/prometheus"
  namespace: sock-shop
  labels:
    app: queue-master 
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: queue-master
    
---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: sock-shop
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
    
---

apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: sock-shop
  labels:
    app: shipping
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: shipping
    
---

apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: sock-shop
  labels:
    app: user-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: user-db

---

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: sock-shop
  labels:
    app: user 
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: user